#!/bin/bash

pwdir=${PWD##*/}

ln -s $pwdir/.vimrc ~/.vimrc
ln -s $pwdir/.vim ~/.vim

read -p "Remote Server?" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    ln -s $pwdir/.bashrc ~/.bashrc .
else
	ln -s $pwdir/.zshrc ~/.zshrc
fi
