#!/bin/bash

pwdir=${PWD##*/}

rm -rf ~/.vim
rm -rf ~/.vimrc

ln -s $pwdir/.vimrc ~/.vimrc
ln -s $pwdir/.vim ~/.vim


echo "Setting up zsh..."
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
chsh -s /bin/zsh

ln -s $pwdir/.zshrc ~/.zshrc

# read -p "Remote Server?" -n 1 -r
# if [[ $REPLY =~ ^[Yy]$ ]]
# then
# 	rm -rf ~/.bashrc
#     ln -s $pwdir/.bashrc ~/.bashrc
# else
# 	rm -rf ~/.zshrc
# 	ln -s $pwdir/.zshrc ~/.zshrc
# fi
# echo "\n"
