#!/bin/bash

pwdir=${PWD##*/}

rm -rf ~/.vim
rm -rf ~/.vimrc

ln -s $pwdir/.vimrc ~/.vimrc
ln -s $pwdir/.vim ~/.vim

read -p "Remote Server?" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
	rm -rf ~/.bashrc
    ln -s $pwdir/.bashrc ~/.bashrc
else
	rm -rf ~/.zshrc
	ln -s $pwdir/.zshrc ~/.zshrc
fi
echo "\n"
